addSbtPlugin("org.ensime" % "sbt-ensime" % "0.5.1")
//addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M12")
addSbtPlugin("net.ceedubs" %% "sbt-ctags" % "0.2.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
//addSbtPlugin("com.dscleaver.sbt" % "sbt-quickfix" % "0.4.1")
